#include<iostream.h>
#include<conio.h>
   struct stud
   {
     char name[30];
     int dob;
     int roll;
     int avg;
     inl marks[3];
   }s[5];
   int n;

   void get()
   {
      cout<<"Enter the number of students";
      cin>>n;
      for(i=0;i<n;i++)
      {
	cout<<"Enter your name"
	cin>>name;
	cout<<"Enter the date of birth";
	cin>>dob;
	cout<<"Enter the marks";
	for(j=0;j<3;j++)
	{
	   cin>>

	}
      }





   }
   void main()
      {
      printf("Hello");
      }